import type { Metadata } from 'next';
import { Recursive } from 'next/font/google';
import './globals.css';

const recursive = Recursive({
  weight: ['300', '400', '500', '600', '700', '800'],
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Chat App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className='dark'
    >
      <body className={`${recursive.className} antialiased`}>{children}</body>
    </html>
  );
}
